version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - /Users/brummerm/Documents/ClassWebsite:/var/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: F22plane!
      MYSQL_DATABASE: cs_course_submissions.sql
    volumes:
      - /Users/brummerm/Documents/ClassWebsite/www/uploads:/var/www/html/uploads
volumes:
  db_data: